version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: "@yext/rtf-converter"
    versions:
    - 1.3.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.9
    - 7.13.10
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.7
    - 7.13.10
  - dependency-name: "@babel/runtime-corejs3"
    versions:
    - 7.12.5
    - 7.13.10
  - dependency-name: i18next
    versions:
    - 19.8.4
    - 19.9.2
  - dependency-name: css-vars-ponyfill
    versions:
    - 2.4.2
    - 2.4.3
  - dependency-name: gulp-uglify-es
    versions:
    - 2.0.0
  - dependency-name: rollup-plugin-babel
    versions:
    - 4.4.0
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: ini
    versions:
    - 1.3.7
    - 1.3.8
