name: Run acceptance tests

on:
  workflow_call:
    inputs:
      concurrency:
        required: false
        type: string
        default: 3

jobs:
  headless_acceptance:
    name: Headless Acceptance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npx testcafe -c ${{ inputs.concurrency }} "chrome:headless" --config-file ./.github/testcafe.json -q
