name: Build and deploy

on:
  push:
    branches-ignore:
      - develop
      - master
      - hotfix/**
      - feature/**-i18n
      - release/**

jobs:
  call_acceptance-1:
    uses: ./.github/workflows/acceptance.yml
    with:
      concurrency: 1

  call_acceptance-2:
    uses: ./.github/workflows/acceptance.yml
    with:
      concurrency: 2

  call_acceptance-3:
    uses: ./.github/workflows/acceptance.yml
    with:
      concurrency: 3

  call_acceptance-4:
    uses: ./.github/workflows/acceptance.yml
    with:
      concurrency: 4

  call_acceptance-5:
    uses: ./.github/workflows/acceptance.yml
    with:
      concurrency: 5

concurrency:
  group: ci-build-and-deploy-${{ github.ref }}-1
  cancel-in-progress: true