name: Build and deploy search bar

on:
  push:
    tags:
      - 'search-bar-v*'
    branches:
      - 'search-bar-v*' ##FOR TESTING ONLY

jobs:
  call_build:
    uses: ./.github/workflows/build.yml
    with:
      build_script: build-search-bar-only
  
  call_misc_tests:
    uses: ./.github/workflows/miscellaneous_tests.yml

  call_acceptance_search_bar:
    uses: ./.github/workflows/acceptance_search_bar.yml
    needs: call_build
    secrets:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

  call_extract_versions:
    uses: ./.github/workflows/extract_versions.yml

concurrency:
  group: ci-build-and-deploy-i18n-${{ github.ref }}-1
  cancel-in-progress: true