name: Build and deploy

on:
  push:
    branches: [dev/*]

jobs:
  build:
    uses: yext/answers-search-ui/.github/workflows/build.yml@dev/build-workflow

  unit_test:
    uses: yext/answers-search-ui/.github/workflows/unit_test.yml@dev/build-workflow

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build-output artifact
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist/

      # The "build" directory is now available inside this job
      - name: Test view dist folder
        run: ls dist