name: Build and deploy # Note: Deployment will be added in a future PR 

on:
  push:
    branches-ignore:
      - develop
      - master
      - support/**
      - hotfix/**
      - feature/**-i18n
      - release/**

jobs:
  call_build:
    uses: yext/answers-search-ui/.github/workflows/build.yml@feature/gh-action-migration

  call_unit_test:
    uses: yext/answers-search-ui/.github/workflows/unit_test.yml@feature/gh-action-migration
    needs: call_build
  
  call_deploy:
    uses: yext/answers-search-ui/.github/workflows/deploy.yml@dev/gh-s3-deploy
    needs: call_unit_test
    with:
      directory: dev/gh-s3-deploy
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


concurrency:
  group: ci-build-and-deploy-${{ github.ref }}-1
  cancel-in-progress: true