name: Build and deploy

on:
  push:
    branches-ignore:
      - develop
      - master
      - hotfix/**
      - feature/**-i18n
      - release/**

jobs:
  call_build:
    uses: ./.github/workflows/build.yml

  call_acceptance:
    uses: ./.github/workflows/acceptance.yml
    needs: call_build
    secrets:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

concurrency:
  group: ci-build-and-deploy-${{ github.ref }}-1
  cancel-in-progress: true