name: Build and deploy search bar

on:
  push:
    branches: [dev/*]

jobs:
  build:
    uses: yext/answers-search-ui/.github/workflows/build.yml@dev/build-workflow
    with:
      build_script: build-search-bar-only

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build-output artifact
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist/

      # The "build" directory is now available inside this job
      - name: Test view dist folder
        run: ls dist

concurrency:
  group: ci-build-and-deploy-search-bar-${{ github.ref }}-1
  cancel-in-progress: true