name: Run unit tests

on:
  workflow_call:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - name: Download build-output artifact
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist/
      - name: Run unit tests
        run: npm run test