name: Run unit tests

on:
  workflow_call:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Download build-output artifact
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist/
      - name: Run unit tests
        run: npm run test